export const members = {
  professors: [
    {
      name: 'Dr. Shibayan Roy',
      userId: 'shibayan',
      role: 'Assistant Professor',
      department: 'Materials Science Center, Indian Institute of Technology, IIT-Kharagpur 721302, India',
      contact: {
        website: ['https://sites.google.com/site/shibayansdreams/home'],
        researcherId: ['http://www.researcherid.com/rid/E-4225-2012'],
        email: ['shibayan@matsc.iitkgp.ernet.in'],
        phone: ['+913222283962'],
      },
      imageFormat: 'jpeg',
    },
  ],
  current: [
    {
      name: 'Dr. Mrinmoy Garai',
      userId: 'mrinmoy',
      role: 'Post Doctoral Fellow',
      year: '2017',
      project: 'Processing, microstructure and mechanical properties of high-strenth Mica and Leucite based glass-ceramics',
      previousEducation: 'Ph. D. (Chemistry), Jadavpur University, 2016',
      workExperience: 'CSIR-Central Glass & Ceramic Research Institute, Kolkata, India',
      contact: {
        email: ['mrinmoygarai@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
    {
      name: 'Souvik Sahoo',
      userId: 'souvik',
      role: 'Post Doctorial Fellow',
      year: '2016',
      project: 'Structure-processing-property correlation in Titanium alloys',
      previousEducation: 'M.Tech in Materials Engineering from Indian Institute of Engineering Science and Technology (IIEST), Shibpur',
      contact: {
        email: ['sahoo.souvik@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
    {
      name: 'Ashoktaru Chakraborty',
      userId: 'ashok',
      role: 'Post Doctoral Fellow',
      year: '2017',
      project: 'Shear banding in materials (metals, alloys and composites)',
      previousEducation: 'M.Tech in Materials Engineering from Indian Institute of Engineering Science and Technology (IIEST), Shibpur',
      contact: {
        email: ['ashoktaru@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
    {
      name: 'Samarendra Roy',
      userId: 'sam',
      role: 'Post Doctoral Fellow',
      year: '2017',
      project: 'Design and development of high temperature high strength Aluminum alloys by nanostructural engineering',
      previousEducation: 'M.Sc in Physics, Presidency University, Kolkata',
      contact: {
        email: ['samarendra@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
    {
      name: 'Sushmita Sharma',
      userId: 'sushmita',
      role: 'MTech',
      year: '2017',
      project: 'Microstructure and mechanical response of various coatings (HAp, Al2O3-TiO2) on additive manufactured (LENS) Ti-6Al-4V alloy',
      previousEducation: 'B. Tech in Nanotechnology from Central university of Jharkhand, Ranchi, Jharkhand',
      contact: {
        email: ['sushms21@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
    {
      name: 'Biswajit M Patra',
      userId: 'biswajit',
      role: 'MTech',
      year: '2017',
      project: 'Microstructure evolution and mechanical response of mica-based machinable glass-ceramics under microwave heating',
      previousEducation: 'B. Tech in Ceramic Engineering from National Institute of Technology Rourkela, Odisha',
      contact: {
        email: ['biswajitpatra@iitkgp.ac.in'],
      },
      imageFormat: 'jpeg',
    },
  ],
  alumni: [
    {
      name: 'Anoop Kumar Maurya',
      userId: 'anoop',
      role: 'MTech',
      year: '2016',
      previousEducation: 'M.Sc General Chemistry (VNIT Nagpur), July 2014 – Jul 2016',
      currentStatus: 'Doctoral student at School of Materials Science and Engineering, Gyeongsang National University, South Korea',
      imageFormat: 'jpeg',
    },
    {
      name: 'Sunil Yadav',
      userId: 'sunil',
      role: 'MTech',
      year: '2015',
      previousEducation: 'B.E. in Metallurgical Engineering from O.P. Jindal Institute of Technology, Raigarh, Chattisgarh',
      currentStatus: 'Preparing for UPSC',
      imageFormat: 'jpeg',
    },
    {
      name: 'Silva Basu',
      userId: 'silva',
      role: 'MTech',
      year: '2015',
      previousEducation: 'B Tech in Metallurgical and Materials Engineering from Jadavpur University',
      currentStatus: 'Doctoral student at Karlsruhe Institute of Technology, Germany',
      imageFormat: 'jpeg',
    },
    {
      name: 'Anuja P. Joshi',
      userId: 'anuja',
      role: 'MTech',
      year: '2015',
      previousEducation: 'B Tech in Metallurgical and Materials Engineering from Jadavpur University',
      currentStatus: 'Doctoral student at Karlsruhe Institute of Technology, Germany',
      imageFormat: 'png',
    },
  ],
}
